
name: chat_user
description: A new Flutter project.
publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:   # Corrected this line
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0
  path_provider: ^2.0.8
  dio: ^4.0.6
  image: ^4.0.17
  provider: ^6.0.2
  photo_view: ^0.14.0   # 图片预览
  device_info_plus: ^8.2.2
  shared_preferences: ^2.0.13 # 数据持久化缓存
  flutter_svg: ^1.0.3
  flutter_styled_toast: ^2.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  number_display: ^3.0.0
  timeline_tile: ^2.0.0  #进度条
  flutter_slidable: ^3.0.0
  google_fonts: ^2.3.1 #pdf 文件需要的字段，不能删除
  desktop_drop: ^0.4.1
  permission_handler: ^9.2.0
  image_picker: ^0.8.6
  number_selection: ^1.0.0
  card_swiper: ^2.0.4  # 轮番图片
  syncfusion_flutter_xlsio: ^20.2.39-beta #到处excel文件用 pagckage
  pretty_qr_code: ^2.0.3  #生成qrcode
  flutter_image_compress: ^1.1.3  # 图片压缩
  image_viewer: ^1.5.0
  excel: ^2.0.1
  file_picker: ^5.2.7
  url_launcher: ^6.1.10
  calendar_date_picker2: ^0.5.1 #日期选择
  webview_flutter: ^3.0.0
  flutter_macos_webview: ^0.0.6
  webview_windows: ^0.2.2
  logger: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  hive_generator: ^2.0.0
  path: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
